apiVersion: standard.oam.dev/v1alpha1
kind: TriggerService
metadata:
  name: kubetrigger-sample-config
  namespace: default
spec:
  # If you ignore selectors, you can use the default TriggerInstance,
  # given the related options are enabled using manager args.
  selector:
    instance: kubetrigger-sample
  # A trigger is a group of Source, Filters, and Actions.
  # You can add multiple triggers.
  triggers:
    - source:
        type: k8s-resource-watcher
        properties:
          # We are interested in ConfigMap events.
          apiVersion: "v1"
          kind: ConfigMap
          namespace: default
          # Only watch update event.
          events:
            - update
      filters:
        - type: cue-validator
          # Filter the events above.
          properties:
              # Filter by validating the object data using CUE.
              # For example, we are filtering by ConfigMap names (metadata.name) from above.
              # Only ConfigMaps with names that satisfy this regexp "this-will-trigger-update-.*" will be kept.
              template: |
                metadata: name: =~"this-will-trigger-update-.*"
      actions:
        # Bump Application Revision to update Application.
        - type: bump-application-revision
          properties:
            namespace: default
            # Select Applications to bump using labels.
            labelSelectors:
              my-label: my-value
