apiVersion: standard.oam.dev/v1alpha1
kind: TriggerService
metadata:
  name: kubetrigger-sample-config
  namespace: default
spec:
  selector:
    app: kubetrigger-sample
  triggers:
    - k8s-resource-watcher:
        apiVersion: "v1"
        kind: ConfigMap
        namespace: default
        events:
          - update
      filters:
        - cue-validator:
            template: |
              // Filter by object name.
              // I used regular expressions here.
              metadata: name: =~"this-will-trigger-update-.*"
      actions:
        - bump-application-revision:
            namespace: default
            labelSelectors:
              my-label: my-value
