# A trigger is a group of Source, Filters, and Actions.
# You can add multiple triggers.
triggers:
  - source:
      template: k8s-resource-watcher
      properties:
        # We are interested in ConfigMap events.
        apiVersion: "v1"
        kind: ConfigMap
        namespace: default
        # Only watch update event.
        events:
          - update
    filters:
      - template: cue-validator
        # Filter the events above.
        properties:
            # Filter by validating the object data using CUE.
            # For example, we are filtering by ConfigMap names (metadata.name) from above.
            # Only ConfigMaps with names that satisfy this regexp "this-will-trigger-update-.*" will be kept.
            template: |
              metadata: name: =~"this-will-trigger-update-.*"
    actions:
      # Bump Application Revision to update Application.
      - template: bump-application-revision
        properties:
          namespace: default
          # Select Applications to bump using labels.
          labelSelectors:
            my-label: my-value
