apiVersion: standard.oam.dev/v1alpha1
kind: TriggerService
metadata:
  name: record-event
  namespace: default
spec:
  triggers:
    - source:
        type: resource-watcher
        properties:
          apiVersion: core.oam.dev/v1alpha1
          kind: WorkflowRun
          events:
            - create
          matchingLabels:
            trigger.oam.dev/watch: "true"
      action:
        type: create-event-listener
    - source:
        type: resource-watcher
        properties:
          apiVersion: apps/v1
          kind: Deployment
          events:
            - update
      filter: context.data.status.readyReplicas == context.data.status.replicas
      action:
        type: record-event
        properties:
          nameSelector:
            fromLabel: "workflowrun.oam.dev/name"
