apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-trigger-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  # We give it the highest privilege just to make sure everyone's config will work.
  # You SHOULD use stricter privileges that suits your needs for security reasons.
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kube-trigger-example
    namespace: default