name: Docs Checks

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch: { }

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check boilerplate
        run: make checklicense

      # Currently not required
      - name: Run Go Generate
        run: make generate

      - name: Check SVG formatting
        run: LINT=true make svgformat