name: Run Go Checks and Build Binaries
on:
  push:
    branches:
      - main
      - release-*
    tags:
      - "v*"
  workflow_dispatch: { }

env:
  GOLANGCI_VERSION: 'v1.47.2'

jobs:
  detect-noop:
    runs-on: ubuntu-latest
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.md", "**.mdx", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
          concurrent_skipping: false

  checks-and-build:
    runs-on: ubuntu-latest
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check boilerplate
        run: make checklicense

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_VERSION }}

      - name: Run Go Generate
        run: make generate

      - name: Show Make Variables
        run: ./make-kt variables

      - name: Get Version
        id: get_version
        run: |
          export VERSION=$(./make-kt version)
          echo ::set-output name=VERSION::${VERSION}

      - name: Build Binaries for All Platforms
        env:
          DIRTY_BUILD: true
        run: ./make-kt all-build

      - name: Upload Artifacts (linux-amd64)
        uses: actions/upload-artifact@v3
        with:
          name: kube-trigger-${{ steps.get_version.outputs.VERSION }}-linux-amd64
          retention-days: 7
          path: bin/kube-trigger-${{ steps.get_version.outputs.VERSION }}/kube-trigger-*-linux-amd64

      - name: Upload Artifacts (darwin-amd64)
        uses: actions/upload-artifact@v3
        with:
          name: kube-trigger-${{ steps.get_version.outputs.VERSION }}-darwin-amd64
          retention-days: 7
          path: bin/kube-trigger-${{ steps.get_version.outputs.VERSION }}/kube-trigger-*-darwin-amd64

      - name: Upload Artifacts (darwin-arm64)
        uses: actions/upload-artifact@v3
        with:
          name: kube-trigger-${{ steps.get_version.outputs.VERSION }}-darwin-arm64
          retention-days: 7
          path: bin/kube-trigger-${{ steps.get_version.outputs.VERSION }}/kube-trigger-*-darwin-arm64
