name: Go
on:
  push:
    branches:
      - main
      - release-*
    tags:
      - "v*"
  workflow_dispatch: { }

env:
  GOLANGCI_VERSION: 'v1.47.2'

jobs:
  detect-noop:
    runs-on: ubuntu-20.04
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.md", "**.mdx", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
          concurrent_skipping: false

  checks:
    runs-on: ubuntu-latest
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate
        run: make generate

      - name: Check boilerplate
        run: make checklicense

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_VERSION }}

  build:
    runs-on: ubuntu-latest
    needs: checks
    if: needs.detect-noop.outputs.noop != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build binaries for linux-amd64
        run: make build-linux_amd64

      - name: Upload artifacts (linux-amd64)
        uses: actions/upload-artifact@v3
        with:
          name: kube-trigger-${{ github.sha }}-linux-amd64
          retention-days: 7
          path: bin/kube-trigger-*-linux-amd64

      - name: Build binaries for linux-arm64
        run: make build-linux_arm64

      - name: Upload artifacts (linux-arm64)
        uses: actions/upload-artifact@v3
        with:
          name: kube-trigger-${{ github.sha }}-linux-arm64
          retention-days: 7
          path: bin/kube-trigger-*-linux-arm64

      - name: Build binaries for darwin-amd64
        run: make build-darwin_amd64

      - name: Upload artifacts (darwin-amd64)
        uses: actions/upload-artifact@v3
        with:
          name: kube-trigger-${{ github.sha }}-darwin-amd64
          retention-days: 7
          path: bin/kube-trigger-*-darwin-amd64

      - name: Build binaries for darwin-arm64
        run: make build-darwin_arm64

      - name: Upload artifacts (darwin-arm64)
        uses: actions/upload-artifact@v3
        with:
          name: kube-trigger-${{ github.sha }}-darwin-arm64
          retention-days: 7
          path: bin/kube-trigger-*-darwin-arm64