name: Build and Push Images
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  workflow_dispatch: { }

jobs:
  release-images:
    name: Release kube-trigger images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show Make variables
        run: make help

      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login docker.io
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build Images
        run: |
          make all-docker-build

      - name: Push Images
        run: |
          make docker-push